### ISSUE TITLE
Release to jitpack or mavenCentral

### ISSUE THREAD

**Issue by Jawnnypoo** [button/button-merchant-android#74]
JCenter is shutting down: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

So, please consider publishing to Jitpack.io or Maven Central instead. The deadline is May 1st.

**Comment by extmkv** [comment]
Any news about this?
We're trying to remove jcenter() from our project and this is the only dependency missing

**Comment by srinikethr** [comment]
any updates on this?

**Comment by najmsheikh** [comment]
Hi all! My sincerest apologies for the delay on this!

You should now be able to pull Merchant Library v1.4.5 directly from `mavenCentral()`

In your root `build.gradle` you may first include the Maven Central repository:
```groovy
allprojects {
    repositories {
        mavenCentral()
        // ...other repos
    }
}
```
and then import the Merchant Library in your project/module `build.gradle` like so:
```groovy
dependencies {
    implementation 'com.usebutton.merchant:button-merchant:1+'
}
```

**Comment by Jawnnypoo** [comment]
I can't find it on https://search.maven.org/ - are you certain it is released?

**Comment by najmsheikh** [comment]
Yep! It generally takes several hours to a day for the _Search_ site to index new packages. However, it is available [on the repository](https://repo1.maven.org/maven2/com/usebutton/merchant/button-merchant/) and Gradle should have no issues pulling from there.

In case you need to refresh dependencies, you can use
```bash
./gradlew :build --refresh-dependencies 
```

**Comment by najmsheikh** [comment]
Hey @Jawnnypoo just following up -- were you able to retrieve the new release?

**Comment by Jawnnypoo** [comment]
Heya, it doesn't work for me for some reason.

**Comment by najmsheikh** [comment]
Could you please post what error you are encountering when trying to fetch the dependency? Would also be helpful to see how you've defined the repositories in your project.

PS the dependency was properly indexed on the Maven Central Search site! You can now find it [here](https://search.maven.org/artifact/com.usebutton.merchant/button-merchant/1.4.5/aar).

**Comment by Jawnnypoo** [comment]
I was mistaken, it works perfectly now. Thanks!

**Comment by najmsheikh** [comment]
Glad to hear it's working!
