### ISSUE TITLE
ButtonMerchant.reportOrder gives 401 error

### ISSUE THREAD

**Issue by yadavkohi** [button/button-merchant-android#82]
### Merchant Library and Android version

**Merchant Library version:**

**Android version:**

**Comment by yadavkohi** [comment]
I am integrating Button Merchant library in Android app. I have configured it and follow the steps provided in doc https://developer.usebutton.com/docs/android-add-merchant-library#add-button-merchant-library

While i call ButtonMerchant.reportOrder(context, order) { throwable ->
            if (throwable == null) {
                // Report order success
                Timber.d("Report Order Success")
            } else {
                // Report order failed
                Timber.d("Report Order Failed : %s", throwable)
            }
         } 
I will be getting error Unsuccessful Request. HTTP StatusCode: 401

Is anybody else facing the same issue.

**Comment by najmsheikh** [comment]
Hi @yadavkohi can you please contact your Button representative. It's likely that "Client Side Order Reporting" is not enabled for your organization.

**Comment by yadavkohi** [comment]
Ok, I will check with button team, One more thing is there any demo app to check the order reporting to button with some static parameters.

**Comment by najmsheikh** [comment]
Sure! You can find one such example [right here](https://github.com/button/button-merchant-android/blob/master/sample/src/main/java/com/usebutton/merchant/sample/KotlinActivity.kt#L85..L122) in this repo. Let me know if you have any questions!
